apiVersion: v1
kind: Service
metadata:
  name: coredns
  annotations:
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
spec:
  ports:
  - name: dns
    port: 53
    targetPort: 1053
    protocol: UDP
  - name: dns-tcp
    port: 53
    targetPort: 1053
    protocol: TCP
  - name: metrics
    port: 9153
    protocol: TCP