helmCharts:
- name: vault
  repo: https://helm.releases.hashicorp.com
  version: 0.20.1
  releaseName: vault
  namespace: vault
  valuesInline:
    server:
      ha:
        enabled: true
        replicas: 3
        apiAddr: "https://vault.oxide.one"
        raft:
          # Enables Raft integrated storage
          enabled: true
      ingress:
        enabled: true
        hosts:
          - host: vault.oxide.one
            paths:
              - /
        tls: 
          - secretName: vault-ingress-tls
            hosts:
              - vault.oxide.one

resources:
  - namespace.yaml