apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./deployments/lon1-digitalocean/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: mainline
  #targetNamespace: default